<?php
$refer=$_GET['ref'];
$r=base64_decode($refer);



?>


 <!DOCTYPE html><html><head>	<title>TechnoCamp</title>	<link rel="icon" type="image/png" sizes="50x50" href="favicon.png">		<meta name="viewport" content="width=device-width, initial-scale=1.0">	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"><script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script><script type="text/javascript" src="./mpld.js"></script><!-- Font awesome 5 --><link href="https://rechargefox.com/campaigns/coin/offer/fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet"><style type="text/css">		@import url('https://fonts.googleapis.com/css?family=Quicksand:400,500,700&subset=latin-ext');html { position: relative; overflow-x: hidden!important;}* { box-sizing: border-box;}body { font-family: 'Quicksand', sans-serif; color: #324e63;}a, a:hover { text-decoration: none;}

.wrapper { width: 100%; width: 100%; height: auto; min-height: 100vh; /*padding: 50px 20px;*/ padding-top: 20px; display: flex; background-image: linear-gradient(-20deg, #ff2846 0%, #6944ff 100%);}.icon-bottom {	font-size: 	2em;	color: linear-gradient(-20deg, #ff2846 0%, #6944ff 100%);}.icon-color{	 background: -webkit-linear-gradient(-20deg, #ff2846 0%, #6944ff 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent;}</style></head><body class="wrapper" style="overflow-x: hidden;">	<div class="d-flex justify-content-center mb-2"> 		<div class="col-lg-8 col-12"> 			<div class="card" style="border-radius: 16px;"> 				<div class="card-body"> 					<div class="row d-flex justify-content-center" style="margin-top: -10px;"> 			</div> 					<div class="row mt-4 d-flex justify-content-center"> 						<h4 style="font-weight: 600; font-size: 1.0rem;">&#9733;INSTANT PAYTM CASHBACK&#9733;</h4> </div> <img src="https://rechargefox.com/campaigns/coin/offer/cb.png" class="mx-auto d-block" width="100px;" height="25px;" style="margin-top: 20px;"> <div class="row mt-4 d-flex justify-content-center text-center"> 	<style>.btn btn-warning text-dark{font-weight: 600;}</style>					<span class="lead"><h4 style="font-weight: 600; font-size: 1.0rem;">COMPLETE OFFER </h4></span> <span class="lead"><h4 style="font-weight: 600; font-size: 1.0rem;">for GET Rs.8 FREE PAYTM CASH INSTANT</h4></span> 					</div> <hr style="border-top: 4px solid rgb(0,0,0,.1);" /> 				 					<div class="row"> 						<!-- <div class="row"> --> 						 						 

		<form action='red.php'		method='GET'>			 							<div class="col-lg-6 col-12 text-center text-md-left"><span class="text-black blockquote"><b>Enter Your Paytm Number</b></span></div> 							<div class="col-lg-6 col-12"> 								<div class="input-group mb-3">	<input type="text" id="mobile" name='mo' class="form-control" required="true" placeholder="Paytm Number" aria-label="Phone number" >

<input type="hidden" name="ref" value="<?php echo $r; ?>">

<button class="btn btn-warning text-dark" name='submit' value="submit">Submit &#9654;</button>

			
									<div class="input-group-append">											</form>		
														</div>								</div> 							</div> 						<!-- </div> --> 					</div> 					<!--<hr style="border-top: 4px solid rgb(0,0,0,.1);" /> 									 									 					<center>		<form method="post" action="https://lootcampaign.in/Refer-And-Earn">		 					<input type="Submit" value="Refer And Earn"> </center> 					</form> 							 					<hr style="border-top: 4px solid rgb(0,0,0,.1);" />--> 							 							<hr style="border-top: 4px solid rgb(0,0,0,.1);" /><div class="col-12 text-center icon-bottom"> 						 										</div> 							 					<hr style="border-top: 4px solid rgb(0,0,0,.1);" /> 					<div class="row"> 						<div class="container"> 							<div class="col-lg-12 col-12 text-left"><span class="text-black blockquote"><b>&#9813; How to Avail this Offer: </b></span></div> 						</div> 						<div class="container ml-3 mt-3"> 							<ul>	 							<li>𝖤𝗇𝗍𝖾𝗋 𝖸𝗈𝗎𝗋 𝖯𝖺𝗒𝖳𝖬 𝖭𝗎𝗆𝖻𝖾𝗋 𝖠𝗇𝖽 𝖢𝗅𝗂𝖼𝗄 𝖲𝗎𝖻𝗆𝗂𝗍.</li>	 							<li> . 2. 𝖱𝖾𝖽𝗂𝗋𝖾𝖼𝗍 𝗍𝗈 𝖮𝗎𝗋 𝖯𝖺𝗋𝗍𝗇𝖾𝗋 𝖶𝖾𝖻 𝖮𝗋 𝖠𝗉𝗉</li> <li>3. 𝖱𝖾𝗀𝗂𝗌𝗍𝖾𝗋 𝖴𝗌𝗂𝗇𝗀 𝖡𝖺𝗌𝗂𝖼𝗌 𝖣𝖾𝗍𝖺𝗂𝗅𝗌 </li> <li> .</li>	 							<li>4. 𝖬𝗎𝗌𝗍 𝖵𝖾𝗋𝗂𝖿𝗒 𝖱𝖾𝗊𝗎𝗂𝗋𝖾𝖽 𝖣𝖾𝗍𝖺𝗂𝗅𝗌 𝖠𝗇𝖽 𝖦𝖾𝗍 𝖨𝗇𝗌𝗍𝖺𝗇𝗍 𝖢𝖺𝗌𝗁𝖻𝖺𝖼𝗄</li>							</ul> 						</div> 					</div> 					<hr style="border-top: 4px solid rgb(0,0,0,.1);" /> 					<div class="row"> 						<div class="container"> 							<div class="col-lg-12 col-12 text-left"><span class="text-black blockquote"><b>&#9813; Terms and Conditions: </b></span></div> 						</div> 						<div class="container ml-3 mt-3"> 							<ul><li>Offer valid only once per user/paytm number/IP address and Device.</li>								<li>Multiple registrations from same user/paytm number/IP address, similar looking usernames and e mail IDs and Device will not be paid.</li>	 							<li>Use only Real Indian Mobile Numbers and genuine mail ID to register in the app.</li> <li>Merchant verifies your account, if they find any Duplicate or Suspicious trasaction, then your cashback may get rejected.</li> <li>Any query related to Cashback will be entertained by Loot Campaign Team. Write email to info@lootcampaign.in.							</ul> 						</div> 					</div> 					<hr style="border-top: 4px solid rgb(0,0,0,.1);" /> 					<div class="row"> 						<!-- <div class="row"> --> 							<!-- <div class="col-3 text-center icon-bottom"> 								<i class="fab fa-facebook icon-color"></i> 							</div> 							<div class="col-3 text-center icon-bottom"> 								<i class="fab fa-instagram icon-color"></i> 							</div> --> 							 						<!-- </div> --> 					</div> 				</div> 			</div> 		</div>	</div></body><div class="col-md-12" style="position:fixed;bottom: 0;width: 100%;background: -webkit-linear-gradient(right, #de1afa,#26b9e4);right: 0;z-index:99;"><a href="http://telegram.dog/lootcampaign" style="text-decoration:underline;text-decoration-color:#fff;font-family: Poppins-Bold;" target="_blank" ><div align="center" style="color: white;font-size:20px; padding: 5px;"><img src="/instant2/join.png" style="width: 35px; margin-right: 5px;"> 𝗝𝗼𝗶𝗻 𝗧𝗲𝗹𝗲𝗴𝗿𝗮𝗺 𝗖𝗵𝗮𝗻𝗻𝗲𝗹</h3> </div></div>
</html>